
blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/josetzunun/YT-Spammer-Purge/discussions
    about: Please create feature requests in the Discussions tab.
